---
title: "NoahProject"
author: "Evan Doughty"
date: "3/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Data Set-up
```{r}
#############################################################################################
setwd("~/Dropbox/CalcanealGearRatio")
calcmeasure <- read.csv("~/Dropbox/CalcanealGearRatio/LACM_CalcaneusMeasurements_2018_8_29.csv", stringsAsFactors=FALSE)
calcmeasure <- calcmeasure[calcmeasure["Measurement.Type.Manual.Photo."] == "Photo",1:14]
calcSpecies <- unique(paste(calcmeasure$Genus, calcmeasure$Species,sep="_"))

MOM.Mat <- read.csv("~/Dropbox/CalcanealGearRatio/MOM_v4.1.csv")
#remove empty rows
MOM.Mat <- MOM.Mat[!MOM.Mat$Species == "",]
#aggregate to get single species entries
MOM.Mat[,"TaxonomicName"] <- paste(MOM.Mat[,"Genus"],MOM.Mat[,"Species"], sep="_")
#MOM.Mat[,"TaxonomicName"] <- gsub(pattern = " ", replacement =  "_", x = MOM.Mat[,"TaxonomicName"],)

MOM.Mat[,"CombinedMass(kg)"] <- MOM.Mat[,"Combined.Mass..g."]/1000
MOM.Mat[,"logMass.Kg"] <- log10(MOM.Mat[,"CombinedMass(kg)"])
MOM.Mat <- MOM.Mat[,c("Order","FAMILY","Genus","Species","TaxonomicName","CombinedMass(kg)","logMass.Kg")]
#combine same species if multiple entires(e.g. Muntiacus_reevesi has separate entries for mainland Asia and Insular)
MOM.Mat <- aggregate(MOM.Mat[,-c(1:5)], by = list(MOM.Mat$Order, MOM.Mat$FAMILY,MOM.Mat$Genus,
                                                  MOM.Mat$Species, MOM.Mat$TaxonomicName), mean)
colnames(MOM.Mat)[1:5] <- c("Order","FAMILY","Genus","Species","TaxonomicName")

ecoMat <- read.csv("~/Dropbox/CalcanealGearRatio/ExtantUngulate_BM_Eco_Mendoza_etal2007.csv")
ecoMat["TaxonomicName"] <- paste(ecoMat[,"Genus"],paste("_",ecoMat[,"Species"],sep=""),sep="")

#############################################################################################
###Analysis
#############################################################################################
getOneSpecimenAverage <- function(this.specimen, calcmeasure) {
	this.measurements <- c("Length.Calc", "Length..medial.", "Length..lateral.", "Width..between.prox.condyles.", "Width..between.distal.condyles.navicular.facet.", "Length.to.Sustentacular.Process", "Length.to.Calcaneoastragular.facet", "Calcaneoastragular.facet.to.cuboid.facet")
	colMeans(calcmeasure[calcmeasure$Catalog.Number== this.specimen, this.measurements], na.rm=TRUE)
}

getSpecimenAverages <- function(calcmeasure) {
	specimen.vec <- sort(unique(calcmeasure$Catalog.Number))
	n <- t(sapply(specimen.vec, function(x) calcmeasure[calcmeasure$Catalog.Number==x, c("Museum.Acronym", "Catalog.Number", "Genus", "Species")][1,]))
	m <- data.frame(n, t(sapply(specimen.vec, getOneSpecimenAverage, calcmeasure)))
	m
}

getSpeciesAverages <- function(measureMat) {
  rownames(measureMat) <- NULL
  species.vec <- sort(unique(measureMat$taxon))
  this.measurements <- c("Length.Calc", "Length..medial.", "Length..lateral.", "Width..between.prox.condyles.", "Width..between.distal.condyles.navicular.facet.", "Length.to.Sustentacular.Process", "Length.to.Calcaneoastragular.facet", "Calcaneoastragular.facet.to.cuboid.facet")
  tst <- species.vec[1]
  this.species <- tst
  spMat <-matrix(nrow=length(species.vec),ncol = length(this.measurements))
  for(jj in seq(1, length(species.vec),1))
  {
    this.species <- species.vec[jj]
    spMat[jj,] <- colMeans(measureMat[measureMat$taxon == this.species, this.measurements], na.rm=TRUE)
  }
  colnames(spMat) <- this.measurements
  rownames(spMat) <- species.vec
  spMat
}

m <- getSpecimenAverages(calcmeasure)
m$taxon <- paste(m$Genus, tolower(m$Species), sep="_")
#m$R2 <- m$Length.to.Calcaneoastragular.facet/m$Calcaneoastragular.facet.to.cuboid.facet #this is based on the figure caption
m$R2 <- m$Calcaneoastragular.facet.to.cuboid.facet/m$Length.to.Calcaneoastragular.facet
#m$R2  <- m$Length.to.Calcaneoastragular.facet/m$Length.Calc #this is based on the designation listed in the figure
m$R3 <- m$Length.Calc/m$Length.to.Sustentacular.Process
m$A1 <- rowMeans(m[,c("Length..medial.", "Length..lateral.")], na.rm=TRUE)/rowMeans(m[,c("Width..between.prox.condyles.", "Width..between.distal.condyles.navicular.facet.")], na.rm=TRUE)
m$habitat <- ecoMat$Habitat[match(m$taxon, ecoMat$TaxonomicName)]
m$BM <- MOM.Mat$logMass.Kg[match(m$taxon, MOM.Mat$TaxonomicName)]

#family
m$Family <- MOM.Mat$FAMILY[match(m$taxon, MOM.Mat$TaxonomicName)]
#order
#family
m$Order <- MOM.Mat$Order[match(m$taxon, MOM.Mat$TaxonomicName)]

##remove Perissodactyls (3 species)
m <- m[!m$Order == "Perissodactyla",]

##species level
m.sp <- as.data.frame(getSpeciesAverages(m))
m.sp$taxon <- row.names(m.sp)
#m$R2 <- m$Length.to.Calcaneoastragular.facet/m$Calcaneoastragular.facet.to.cuboid.facet #this is based on the figure caption
m.sp$R2 <- m.sp$Calcaneoastragular.facet.to.cuboid.facet/m.sp$Length.to.Calcaneoastragular.facet
#m$R2  <- m$Length.to.Calcaneoastragular.facet/m$Length.Calc #this is based on the designation listed in the figure
m.sp$R3 <- m.sp$Length.Calc/m.sp$Length.to.Sustentacular.Process
m.sp$A1 <- rowMeans(m.sp[,c("Length..medial.", "Length..lateral.")], na.rm=TRUE)/rowMeans(m.sp[,c("Width..between.prox.condyles.", "Width..between.distal.condyles.navicular.facet.")], na.rm=TRUE)
m.sp$habitat <- ecoMat$Habitat[match(m.sp$taxon, ecoMat$TaxonomicName)]
m.sp$BM <- MOM.Mat$logMass.Kg[match(m.sp$taxon, MOM.Mat$TaxonomicName)]

#reorder
m.sp <- m.sp[,c(9,13,1:8,14, 10:12)]
m.sp <- m.sp[complete.cases(m.sp),] #68 species
m <- m.sp
#############################################################################################
```

```{r}
habitat.colors <- c("dodgerblue", "chartreuse", "goldenrod1")
```

####################################################################################################
#2-Habitat Hypothesis (OH and MH+CH)
```{r}
library(ggfortify)
m <- m.sp
dropCol <- c(1:3,11:14)
df <- log(m[,-dropCol])
m$habitat <- gsub("MH","CH",m$habitat)
habitat.colors <- gsub("CH","dodgerblue", m$habitat)
habitat.colors <- gsub("OH","goldenrod1", habitat.colors)

df <- scale(df)
```

##K-means
```{r}
set.seed(1)
#set-symbols for pch
ksym <- gsub("OH",16, m$habitat)
ksym <- gsub("MH",18, ksym)
ksym <- gsub("CH",18, ksym)
ksym <- as.numeric(ksym)

df.kmean <- kmeans(df, 2)

kcol <- gsub(1, "red", df.kmean$cluster)
kcol <- gsub(2, "darkgreen", kcol)
kcol<- gsub(3, "blue", kcol)

autoplot(df.kmean, data = m, size = 0.1) +
  geom_point(shape = ksym, colour = kcol, size = 2) 

```

##Discriminant Analysis
###Linear Discriminant Analysis
```{r}
library(lfda)
library(MASS)

lda.tst_MHCH <- lda(x = as.matrix(df), grouping = m$habitat)
plot(lda.tst_MHCH, col = habitat.colors[m$habitat])
```

###Local Fisher Discriminant Analysis (LFDA)
```{r}
model1_MHCH <- lfda(df, m$habitat, 3, metric="plain")
autoplot(model1_MHCH, data = m, frame = TRUE, frame.colour = 'habitat', size=0.1)+
  geom_point(shape = ksym, size=2) 
```

```{r}
autoplot(model1_MHCH, data = m, x=2, y=3,frame = TRUE, frame.colour = 'habitat', size=0.1)+
  geom_point(shape = ksym, size=2) 
```
###Kernal Local Fisher Discriminant Analysis (KLFDA)
```{r}
model2_MHCH <- klfda(kmatrixGauss(df), m$habitat, 3, metric="plain")
autoplot(model2_MHCH, data = m, frame = TRUE, frame.colour = 'habitat', size=0.1)+
  geom_point(shape = ksym, size=2) 
```

```{r}
autoplot(model2_MHCH, data = m,x=2,y=3, frame = TRUE, frame.colour = 'habitat', size=0.1)+
  geom_point(shape = ksym, size=2) 
```

###Semi-supervised Local Fisher Discriminant Analysis (SELF)
```{r}
model3_MHCH <- self(df, m$habitat, beta = 0.1, r = 3, metric="plain")
autoplot(model3_MHCH, data = m, frame = TRUE, frame.colour = 'habitat', size=0.1)+
  geom_point(shape = ksym, size = 2) 
```

```{r}
autoplot(model3_MHCH, data = m, x=2,y=3, frame = TRUE, frame.colour = 'habitat', size=0.1)+
  geom_point(shape = ksym, size =2) 
```



